### ISSUE TITLE
Jean-Philippe Paradis consistently applies his official policies. I can't stop crying.

### ISSUE THREAD

**Issue by lispm** [Hexstream/common-lispers.hexstreamsoft.com#14]
He added people to his website without asking them and refuses to delete people on request.

I never wanted to be listed with my name, my social media accounts, my homepage. I never gave permission to use my data.

I actually want to stay as far away from Jean-Philippe Paradis website as possible. 
Read his insane policies to be warned.

This a gross violation of the 'General Data Protection Regulation'.

https://eugdpr.org/the-regulation/

**Comment by Hexstream** [comment]
Hello again. Ready for another round I see...
Thank you for displaying some kind of basic composure this time around, I suppose.

> He added people to his website without asking them and refuses to delete people on request.

That is quite correct.

> I never wanted to be listed with my name, my social media accounts, my homepage.

That is quite clear.

> I never gave permission to use my data.

Correct again, but my understanding is that **nobody needs permission to republish information that people willingly publicly disclose about themselves**. I already mentioned this to you [directly](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/2#issuecomment-483356457).

I also already [mentioned](https://web.archive.org/web/20190415182329/https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/13#issuecomment-483319564) to you that, "If you didn't wish your data to be public, then you shouldn't have made it public...".

> I actually want to stay as far away from Jean-Philippe Paradis website as possible.

I encourage you to do so, since you hate me with such a passion.
You'll miss out on a lot of relevant information, but that's life...

The [footer](https://common-lispers.hexstreamsoft.com/#footer) and [policies](https://common-lispers.hexstreamsoft.com/policies/) make it pretty clear that this is neither a list of people I endorse nor a list of my political supporters...

> This a gross violation of the 'General Data Protection Regulation'.
>
> https://eugdpr.org/the-regulation/

I am really quite sure the GDPR does not forbid republishing facts that people willingly publicly disclose about themselves. If it does, then please point me exactly where that is, as I do not currently have the resources to review the entire GDPR.

PS: Upvoting yourself won't save you. :joy:

**Comment by lispm** [comment]
> nobody needs permission to republish information that people willingly publicly disclose about themselves. I already mentioned this to you directly.

That's wrong. Aggregating data, including unpublished data (!!!) is a violation, especially since I requested to have my data be removed. You have never documented where you got the data from - so who knows what you did and whether people have disclosed it or not.

Besides, it is good style to ask people BEFORE you create a public list aggregating data about them. Data which you assume to be true.

Again, I REQUEST TO BE DELISTED.

**Comment by Hexstream** [comment]
Somehow, deleting messages in shame after I debunk them has become a staple of Rainer Joswig's "strategy".
**Protip: Don't post messages if you can't take responsibility for them.**
Anyway, here is his original message that I was replying to (may miss some edits), my reply is after the double break line thing:

>> nobody needs permission to republish information that people willingly publicly disclose about themselves. I already mentioned this to you directly.
>
> That's wrong. Aggregating data, including unpublished data (!!!) is a violation, especially since I requested to have my data be removed. You have never documented where you got the data from - so who knows what you did and whether people have disclosed it or not.
>
> Besides, it is good style to ask people BEFORE you create a public list aggregating data about them.  Data which you assume to be true.
> 
> Again, I REQUEST TO BE DELISTED.

---------------
---------------

> including unpublished data (!!!)

If it had been "unpublished data", then I wouldn't have trivially found it...

> especially since I requested to have my data be removed.

You have requested me to remove data that you have willingly publicly disclosed about yourself. I don't believe I am obligated to do that. It seems to me this would be the death of journalism, for one thing.

> You have never documented where you got the data from

That's correct. I got the data from simple google searches and stuff.

And of course, my somewhat extensive knowledge of the Common Lisp community that I have accumulated over the last 10+ years has helped a great bit. Note that I am almost completely unaware of any "proprietary" bits of data in the Common Lisp community (or any others). I can't "leak" data that I never had...

I believe anyone could easily reconstruct the same dataset from first principles.
Do let me know if you find any data in the list that can be proven to not have been public at the time I collected it. Good luck.

> so who knows what you did and whether people have disclosed it or not.

Don't be ridiculous. Try to find the same information by yourself, you'll see that it's all public data. No FUD, please.

> Besides, it is good style to ask people BEFORE you create a public list aggregating data about them. 

I don't deny that it's [Common Sense™](https://twitter.com/HexstreamSoft/status/1114587647727554562) (slightly NSFW, My Little Snowflake) but the political landscape demanded a different strategy.

**Comment by no-defun-allowed** [comment]
[In internet culture, listing information about various people without their permission (or notifying them) is considered a dick move.](https://www.youtube.com/watch?v=rWY47bW8K3s) (So is calling someone a snowflake, but no one seems to recognize *that*.) It is public data, but you are taking steps to make it easier to locate (possibly non-Lisp related) accounts of people, which feels quite like doxxing to me. In many places, [it is also illegal](https://en.wikipedia.org/wiki/Right_to_be_forgotten#Recognition) to not remove people's information from your list when they request so. There is also [a good opt-in list of people on CLiki](https://www.cliki.net/person) which does respect what people are comfortable publishing.

I'll keep my statement then: no matter what your policies are, **this is illegal, or at least a very inconsiderate decision**.

**Comment by Hexstream** [comment]
> In internet culture, listing information about various people without their permission (or notifying them) is considered a dick move.

I believe I am fairly well-versed in internet culture, and I'm pretty sure this is the first time I hear of this with respect to public information that people willingly publicly disclose about themselves, especially given the fairly neutral type of information that the Common Lispers list processes.

I think a much more common and beloved meme is, "**it's easier to ask for forgiveness than permission**". (Especially useful for very independent-minded and "politically fucked" people like me who have a lot to do and are fairly unlikely to get permission for anything.)

> So is calling someone a snowflake, but no one seems to recognize *that*.

Rainer Joswig (lispm) once [qualified](https://github.com/exercism/common-lisp/issues/206#issuecomment-421629252) [my twitter](https://twitter.com/HexstreamSoft) as "strictly NSFW".
I think that's completely *bonkers* and that it does justify calling him a "snowflake".

> which feels quite like doxxing to me

I think it is patently obvious that the Common Lispers list has nothing whatsoever to do with doxxing.

> In many places, [it is also illegal](https://en.wikipedia.org/wiki/Right_to_be_forgotten#Recognition) to not remove people's information from your list when they request so.

Have you actually read significant parts of that page? My understanding is that "Right to be forgotten" is very strongly related to *huge* search engines and *private* information, and hence is *absurdly unrelated* to the Common Lispers list.

> There is also [a good opt-in list of people on CLiki](https://www.cliki.net/person) which does respect what people are comfortable publishing.

[I'm not sure about "good".](https://twitter.com/HexstreamSoft/status/1114312882643177472) Have you actually reviewed its contents? (I have not, and I do not want to do so right now for lack of interest and time. I might eventually use it to find more Common Lispers to add to the Common Lispers list...)

Are you sure that list is "opt-in"? While I'm sure most of the pages were created by the persons themselves, my understanding is that anyone could create a page about someone else there. I am not sure if that has ever happened or if there is any implicit rule against it. I am pretty sure any removal request by a person on that list would be honored, though. But that's besides the point, as far as I'm concerned...

(On second thought, did you mean "opt-out"?...)

> I'll keep my statement then

??? Are you referring to previous edits or something? I won't dig through that. ;P

> no matter what your policies are, **this is illegal, or at least a very inconsiderate decision**.

I strongly disagree with your baseless claim.
You're going to need some facts and logic to convince me.
And vague feelings unsupported by facts and logic won't be too useful as a rhetorical device.

**Comment by no-defun-allowed** [comment]
>I believe I am fairly well-versed in internet culture, and I'm pretty sure this is the first time I hear of this with respect to public information that people willingly publicly disclose about themselves, especially given the fairly neutral type of information that the Common Lispers list processes.

Did you not have stupid rumours in your school when you were a child? Nothing like some kid running up to their friends shouting "JEAN PICKS HIS NOSE, JEAN PICKS HIS NOSE"? That's public information, but it's not a nice use of public information, and no one asked you if they could tell everyone you pick your nose. If someone wants to be identified as a Lisp programmer, then they can do so themselves, it's not your business to make that choice for them. If I find your account on any brony forums, I'll make a PR to add those in since that is an account of a Lisp programmer too.

>I think a much more common and beloved meme is, "it's easier to ask for forgiveness than permission".

You aren't asking for forgiveness or permission, unless you can tell us how lispm or jackdaniel could get their names off this list without dying or quitting programming.

>Rainer Joswig (lispm) once qualified my twitter as "strictly NSFW".

It'd be a good start to not call yourself a "clopper" in your description. 

>Have you actually read significant parts of that page? My understanding is that "Right to be forgotten" is very strongly related to huge search engines and private information, and hence is absurdly unrelated to the Common Lispers list.

The "right to be forgotten" is not only constrained to huge search engines and private information. Those are just examples and don't cover everything. [You certainly cannot use any information about anyone without their permission.](https://law.stackexchange.com/questions/26391/does-the-gdpr-allow-me-to-access-data-from-public-sources-store-it-and-anaylize)

>??? Are you referring to previous edits or something? I won't dig through that. ;P

Typo. It should be "I'll keep my statement short:" 

>I strongly disagree with your baseless claim. You're going to need some facts and logic to convince me.

H̶e̶x̶s̶t̶r̶e̶a̶m̶'̶s̶ ̶s̶t̶a̶l̶k̶i̶n̶g̶ ̶w̶e̶b̶s̶i̶t̶e̶ ̶s̶t̶a̶t̶e̶d̶ ̶i̶l̶l̶e̶g̶a̶l̶ ̶u̶s̶i̶n̶g̶ ̶F̶A̶C̶T̶S̶ ̶a̶n̶d̶ ̶L̶O̶G̶I̶C̶ Here are your bloody facts and logic.

**Comment by Hexstream** [comment]
>> I believe I am fairly well-versed in internet culture, and I'm pretty sure this is the first time I hear of this with respect to public information that people willingly publicly disclose about themselves, especially given the fairly neutral type of information that the Common Lispers list processes.
>
> Did you not have stupid rumours in your school when you were a child? Nothing like some kid running up to their friends shouting "JEAN PICKS HIS NOSE, JEAN PICKS HIS NOSE"? That's public information, but it's not a nice use of public information, and no one asked you if they could tell everyone you pick your nose.

Your "analogy" is comically and completely unrelated.

(edit: And my reply that you are quoting and responding to is already contradicting your "analogy" on multiple points. I would appreciate greater intellectual rigor on your part.)

"Highlights" aside, the Common Lispers list processes **easily verifiable willingly publicly disclosed  objective neutral facts about adults only**. (edit: Some measure of subjectivity is sometimes involved in selecting what to include as "Website" or "Blog" or "Portal", but this is all done in good faith.)

As for the "Highlights", a good faith effort has been made to identify the best and most positive Common Lisp contributions of each individual. As this is not always objective or easily verifiable, help is requested from the Common Lispers list members to help correct that information if their best contributions have not been correctly identified, but I will not proactively contact them for that purpose. 

(In one single case during development I contacted one single person to ask them about their best contributions because they seemed to have a few worthwhile ones but I was absolutely unable to tell which was their best, I did not want to single them out as being the only one with zero highlights. I could (and should) just have picked 1 or 2 contributions essentially at random which means I wouldn't have to type this disclosure right now, and there will be no further exceptions.)

> If someone wants to be identified as a Lisp programmer, then they can do so themselves, it's not your business to make that choice for them.

If someone willingly publicly discloses their open-source Common Lisp contributions online, then they are willingly publicly disclosing that they are an open-source Common Lisp contributor, by definition. They are making the disclosure choice themselves, I am merely reporting on the *fait accompli*.

> If I find your account on any brony forums, I'll make a PR to add those in since that is an account of a Lisp programmer too.

That won't work, per the already firmly established policies and precedents.

The Common Lispers list tracks social media accounts on [a restricted set of platforms only](https://common-lispers.hexstreamsoft.com/preferences/#fields). One *personal* account is tracked per platform for each Common Lispers list member, and if that person has additional *strongly Common Lisp related* accounts on the same platform then they are also eligible. See [the Zach Beane entry](https://common-lispers.hexstreamsoft.com/#Zach_Beane) for an extreme example of multiple eligible accounts on the same platforms. See [the Pavel Penev entry](https://common-lispers.hexstreamsoft.com/#Pavel_Penev) for another example. I don't think there are any others currently.

>> I think a much more common and beloved meme is, "it's easier to ask for forgiveness than permission".
>
> You aren't asking for forgiveness or permission, unless you can tell us how lispm or jackdaniel could get their names off this list without dying or quitting programming.

I am asking for forgiveness for exercising my right to republish their willingly publicly disclosed information for the greater public good.

>> Rainer Joswig (lispm) once qualified my twitter as "strictly NSFW".
>
> It'd be a good start to not call yourself a "clopper" in your description.

No. How so? As [previously said](https://github.com/exercism/common-lisp/issues/206#issuecomment-421629252):

> [...] probably only about 1% or so of my twitter is actually NSFW (especially sexually), unless you count exposing corruption as being NSFW. Anyone who thinks my twitter is "NSFW" really has no idea what a NSFW twitter even looks like and/or is comforting themselves in a convenient lie.

The "clopper" in my twitter description is just a disclosure.
I make only occasional passing mentions about clop on my twitter.
Probably less than 0.5% of my tweets are in any way clop related...

So yeah, I openly question the sanity of anyone who thinks my twitter is "strictly NSFW".

(edit: Also note that I added "clopper" in my twitter bio only on [15 october 2018](https://twitter.com/HexstreamSoft/statuses/1051806434831290369)), which was exactly one month after Rainer Joswig made his comment about my twitter being "strictly NSFW", on [15 september 2018](https://github.com/exercism/common-lisp/issues/206#issuecomment-421629252).)

> The "right to be forgotten" is not only constrained to huge search engines and private information. Those are just examples and don't cover everything. [You certainly cannot use any information about anyone without their permission.](https://law.stackexchange.com/questions/26391/does-the-gdpr-allow-me-to-access-data-from-public-sources-store-it-and-anaylize)

Actually, the link that you posted conveniently says that I can! Thank you!

> Data can only be processed if there is at least one lawful basis to do so. The lawful bases for processing data are:
> [...]
> processing is necessary for the performance of a task carried out in the public interest [...]
> [...]
> processing is necessary for the purposes of the legitimate interests pursued by the controller [...]

Check out [the initial announcement](https://twitter.com/HexstreamSoft/status/1111796378286596096) for the Common Lispers list (do note that most of that subsequent thread is strictly off-topic for this issue), and also the [policies](https://common-lispers.hexstreamsoft.com/policies/). I think it is patently obvious that the Common Lispers list is in the public interest, and that promoting Common Lispers and their best works to help the community grow is a legitimate interest pursued by myself.

>> I strongly disagree with your baseless claim. You're going to need some facts and logic to convince me.
>
> H̶e̶x̶s̶t̶r̶e̶a̶m̶'̶s̶ ̶s̶t̶a̶l̶k̶i̶n̶g̶ ̶w̶e̶b̶s̶i̶t̶e̶ ̶s̶t̶a̶t̶e̶d̶ ̶i̶l̶l̶e̶g̶a̶l̶ ̶u̶s̶i̶n̶g̶ ̶F̶A̶C̶T̶S̶ ̶a̶n̶d̶ ̶L̶O̶G̶I̶C̶ Here are your bloody facts and logic.

I can't make sense of that, and it appears to be of the realm of confused feelings, not facts and logic.

**Comment by lispm** [comment]
What's going on here, Jan-Phillipp ? Instead of arguing with people and dancing around the issue: just delete me from your website.

**Comment by Hexstream** [comment]
Rainer Joswig (lispm) said:

> What's going on here, Jan-Phillipp ? Instead of arguing with people and dancing around the issue: just delete me from your website.

What a great gift! You are hereby blocked from all my projects for your [multiple insane transgressions](https://twitter.com/HexstreamSoft/status/1118733322602057734).

I will soon produce a detailed public report about your putrid insanity and will report you to GitHub in an attempt to stop you from harassing anyone else.

([See announcement.](https://twitter.com/HexstreamSoft/status/1120000019493457921))

Farewell, Rainer Joswig (lispm).

![Fuck you. :heart:](https://ponies.hexstream.net/images/reactions/rainbow-dash-fuck-you.png)

**Comment by Hexstream** [comment]
On second thought, it will probably be the public report first (soon), *then* the reporting to GitHub.

**Comment by dkochmanski** [comment]
I'm observing this thread with unhealthy fascination. You need to seek professional help Jean, and I really mean it. You hurt mostly yourself (and I don't really care) and make a bad impression of the community by your behavior.

If spamming your issue threads is enough to "get banned" from your resources is enough I'll be happily to do that. I don't want to be referenced on websites of insane people (because it is like being linked as a "professional medical doctor" on the anti-vaccination proponents community website). 

I'm still waiting for Digital Ocean answer about abuse and violation of my privacy. Making something available on the internet is not the same as making it public. When I put information on the website I give that website explicit right to share this information which is not transitive, just like putting a wallet on the public street doesn't make it a public property.

As the last note (which is truly last, I won't bother to answer any of your remarks): you should be ashamed of yourself. Slandering people, calling them names  - while I can imagine where this comes from (i.e hard experiences), they can't be justified by any means.

**Comment by Hexstream** [comment]
> I'm observing this thread with unhealthy fascination.

Now, imagine what it's like to observe and publicly report on Rainer Joswig's (lispm's) patently corrupt behavior for years and seeing nobody else doing anything about it... But I think that's about to change, unless masses of people are committed to losing all credibility.

> You need to seek professional help Jean, and I really mean it.

Do explain why! This is often used as a rhetorical device, but with no basis in fact whatsoever, it's not too convincing.

> You hurt mostly yourself (and I don't really care) and make a bad impression of the community by your behavior.

Here's what's *really* fascinating: Me helping to build the Common Lisp community and identify its dysfunctions being seen as (or maliciously misreported as) "making a bad impression of the community by my behavior".

> If spamming your issue threads is enough to "get banned" from your resources is enough I'll be happily to do that.

*Minimize* all you want, Daniel Kochmański, but my upcoming extensive public report on Rainer Joswig's putrid insanity and corruption over many years will *optimize* everyone's understanding of the situation. (For everyone who doesn't instinctively close their eyes every time they see an inconvenient truth, at least.)

> I don't want to be referenced on websites of insane people (because it is like being linked as a "professional medical doctor" on the anti-vaccination proponents community website).

Generally true but contextually irrelevant.

> I'm still waiting for Digital Ocean answer about abuse and violation of my privacy.

What a strange thing for you to say after I published my "[Daniel Kochmański (jackdaniel) rushed to send a MALICIOUS, LIBELOUS AND FRAUDULENT complaint to Cloudflare](https://blog.hexstream.xyz/Daniel-Kochma%C5%84ski-jackdaniel-rushed-to-send-a-MALICIOUS-LIBELOUS-AND-FRAUDULENT-complaint-to-Cloudflare/)" article and [publicly notified you about it](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/2#issuecomment-482899557) *more than a week ago*.

I genuinely can't tell if you are merely pretending to still be waiting for an answer from them, or if you truly are deluded enough to believe that they will waste their time replying to your baseless complaint, even after I completely debunked it.

> Making something available on the internet is not the same as making it public. When I put information on the website I give that website explicit right to share this information which is not transitive

Don't willingly publicly disclose facts about yourself on the internet if you don't want those facts about yourself to be publicly known...

> just like putting a wallet on the public street doesn't make it a public property

Your analogy plainly does not translate in context, just as [Rainer Joswig's insane repeated claim that I was somehow "taking him hostage" didn't translate. I asked him FOUR SEPARATE TIMES to explain how his "analogy" translated (while he kept repeating the claim), he never even tried to explain...](https://web.archive.org/web/20190415182329/https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/13#issuecomment-483306760)

> As the last note (which is truly last, I won't bother to answer any of your remarks):

Wouldn't that be great?!? I neither believe nor disbelieve you on this one.

> you should be ashamed of yourself.

I am always eager to feel ashamed about myself when there are good reasons for me to do so, which fortunately happens rarely.

> Slandering people, calling them names - while I can imagine where this comes from (i.e hard experiences), they can't be justified by any means.

***Hilarious fact: I never lie, therefore I never slander.***

Telling inconvenient truths about people is not quite the same as "calling them names". I often call out crummy people for what they are, but only as a conclusion, never as an "argument", and always with supporting evidence, as far as I remember. Do let me know of any alleged lapses you might come across and I'll investigate. My responsiveness has repeatedly been demonstrated.

***Hilarious fact: I am BY FAR the most frequent target of slander in the Common Lisp community. Nobody comes even close.***

[Check this thread](https://twitter.com/HexstreamSoft/status/1112464988038402055) for a nice example of someone repeatedly slandering me only to immediately get debunked each time. Comedy gold.

Again, do check out my awesome "[Daniel Kochmański (jackdaniel) rushed to send a MALICIOUS, LIBELOUS AND FRAUDULENT complaint to Cloudflare](https://blog.hexstream.xyz/Daniel-Kochma%C5%84ski-jackdaniel-rushed-to-send-a-MALICIOUS-LIBELOUS-AND-FRAUDULENT-complaint-to-Cloudflare/)" article. Wouldn't it be great if slanderers like you at least refrained from falsely accusing others of slander? I am sure it is too much to ask, though.

Enjoy! I am looking forward to your lack of further replies!

**Comment by Hexstream** [comment]
[Sorry, slight change of plans.](https://twitter.com/HexstreamSoft/status/1121284781868748800) ;P

**Comment by Hexstream** [comment]
I'm closing this non-issue because it has actually been [completely resolved](https://common-lispers.hexstreamsoft.com/policies/#removal) [since 3 weeks ago](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/commit/a3f553a939875afd37e9ab4201bd828e834aad36), which you'll note was 10 days before this non-issue was even created...

In summary, ***Rainer Joswig expected me to grant him special privileges on the basis that [he is an entitled manchild and a bully](https://twitter.com/HexstreamSoft/status/1118733322602057734).*** **I refused, since acceding to his demands would effectively invalidate my [ironclad policies](https://common-lispers.hexstreamsoft.com/policies/) and validate terrorism as an effective tactic. I am simply not going to destroy or gravely endanger my infrastructure every time someone cries.** Everyone on the wrong side of history has been dancing around the [ironclad policies](https://common-lispers.hexstreamsoft.com/policies/) because they instinctively know that they are unassailable. (And I have seen no evidence that Rainer Joswig has spent more than one minute reading them.)

**Note that only 2 Common Lispers list members have expressed discontent at being included therein, that's LESS THAN 2%. Meanwhile, at least 4 people have expressed satisfaction.**

--------------------------------

Thanks to all participants in this thread, I suppose.

If someone has something **new and relevant** to say about this, they may post **here**.

I don't want the same old shit that has already been rehashed to death to scatter all over the place again, so **note that any new duplicates of this issue that would be posted may be subject to immediate deletion. Also note that posting spam in completely unrelated threads and other obviously moronic behaviors [à la Rainer Joswig](https://twitter.com/HexstreamSoft/status/1118733322602057734), especially if related to this non-issue and/or used as a terrorism "tactic", would likely result in an immediate ban.**

**Comment by mohe2015** [comment]
@Hexstream 
As you qouted GDPR Article 6 says
Pocessing shall be lawful only if and to the extent that at least one of the following applies: 

* processing is necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller;
* processing is  necessary  for  the  purposes  of  the  legitimate interests  pursued by  the  controller or  by  a  third  party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data, in particular where the data subject is a child. 

I'm pretty sure the first sentence doesn't apply here as this is not public interest (although that term shall be interpreted as the respective national law defines it). Public interest is usually only something about politics, etc.

You conveniently omitted the relevant part of the second sentence which probably means that you would have to honor a request for deletion.

You would probably also need to read the Terms of Service of all providers you got the data from to show that you legally process the data.

I'm not a lawyer and don't know the GDPR that well but all aside this is extremely rude behavior.

I won't answer to this because I wouldn't be able to provide further input and also am not interested in doing so but I wanted do put this out here to show that this may not be legal.

Also your website doesn't provide a link to your contact information and to your data protection declaration which I'm pretty sure is illegal.

**Comment by Hexstream** [comment]
Thank you for the polite FUD, but this is definitely in the public interest.

I am confident the Common Lispers list is at least overwhelmingly legal (98%+), and if you have [concerns](https://pics.me.me/concern-30338992.png) and wish the project to achieve 100% legal compliance, consider [sponsoring me](https://github.com/sponsors/Hexstream) to help give me the needed resources to achieve 100% legal compliance, which is currently well beyond my financial means.

I will not deprive the Common Lisp community of an overwhelmingly useful and positive resource over vague FUD.
