### ISSUE TITLE
Add Request

### ISSUE THREAD

**Issue by durrendal** [Hexstream/common-lispers.hexstreamsoft.com#16]
Name: Will Sinatra
IRC Nick: wsinatra 
Gitlab: https://gitlab.com/Durrendal
Linkedin: https://www.linkedin.com/in/will-sinatra/
CL Projects: https://gitlab.com/Durrendal/Paraexec
Alpine Linux Package Maintainer: SBCL, Clisp, Fennel, Clojure

**Comment by Hexstream** [comment]
Thank you for your add request!

[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Will_Sinatra)

I hope this is to your satisfaction.

PS: The Common Lispers list does not (currently) track IRC nicks per se, but since you mentioned it, I'm assuming that's your desired nick, so I assigned you that nick. I would normally have auto-assigned you "durrendal" since that's the one you seem to be using most consistently.

**Comment by durrendal** [comment]
Thanks Jean-Philippe!

I do use Durrendal a lot, but all of my serious FOSS work I do under my own
name. Either way is fine, but I prefer wsinatra so I appreciate it!
