### ISSUE TITLE
please remove me from the list

### ISSUE THREAD

**Issue by dkochmanski** [Hexstream/common-lispers.hexstreamsoft.com#2]
I was not asked nor agreed to publish my aggregated information on this site.

nb: You may consider asking others before publishing their information too. Necessity to opt-out from something you have never subscribed is not the nicest thing.

**Comment by svetlyak40wt** [comment]
:(

**Comment by defunkydrummer** [comment]
Wow... On the other hand you should be on the list, as "the man" for ECL..!

**Comment by dkochmanski** [comment]
I've asked for this more than a week ago. When I look at the website I can still see my name and PR which respects my wish is closed. How hard is it to remove my name from your website after explicit demand? When may I expect my name removed from this page?

**Comment by Hexstream** [comment]
I apologize for the delays. I appreciate your patience. Notably, an important life event requiring immediate attention has kept me busy and delayed the processing of this issue, which is indeed important but unfortunately not as straightforward to resolve as it may appear, as might have been inferred from the applied `Pending further processing` label and its description.

2 days ago, the creator of the corresponding pull request has closed their request, and I took the occasion to [point them](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/pull/4#issuecomment-480375361) to [a tweet](https://twitter.com/HexstreamSoft/status/1113940019788550144) that I had posted the day before, stating that I was indeed "working on a major policy update that will provide some clarifications *and notably address the removal issue*" (emphasis mine). I did not see fit to actively inform you of this fact since I had already publicly stated that I was working on the case on 2 recent occasions (the tweet and my comment pointing to it in the pull request) and I knew that the policy update was imminent. In fact, yesterday I made major progress on the update and I expect to be able to complete it and push it out today.

Note that nobody has been added to the list since launch. So as to best prioritize this issue, **rest assured that I will not add any more people to the list until the removal issue is addressed to my satisfaction**.

Hence, I'll have to implore your patience for a little while longer.
Thank you for your understanding, and sorry for the inconvenience.

**Comment by Hexstream** [comment]
Do note that it is the pull request creator who has closed their request, not me.

**Comment by Hexstream** [comment]
Alright. I just [pushed out](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/commit/a3f553a939875afd37e9ab4201bd828e834aad36) a [major policy update](https://common-lispers.hexstreamsoft.com/policies/). (You may need to `shift-refresh`.)

[Unfortunately, I cannot accede to your removal request](https://common-lispers.hexstreamsoft.com/policies/#removal).
I hope you can see now that there are pretty good reasons for this.

**This issue has not yet been resolved to my satisfaction.
A partial remedy will soon be offered to objectors.**

I'm afraid I'm going to have to implore your patience once more.
Hopefully, learning why I can't just remove you from the list alleviates your pain somewhat.

**Comment by Hexstream** [comment]
It seems I never replied directly to your first comment...

> I was not asked nor agreed to publish my aggregated information on this site.

You are correct, out of [practicality](https://common-lispers.hexstreamsoft.com/policies/#tenets_practicality) concerns I have not contacted any of the first 100 added persons, and out of [consistency](https://common-lispers.hexstreamsoft.com/policies/#tenets_consistency) concerns I don't intend to contact anyone else before adding them, either.

Unfortunately, this has not yet been made clear in the policies, and some confusion has resulted. I apologize for this omission and any inconvenience it may have caused. I am looking to fix this soon.

> nb: You may consider asking others before publishing their information too.

No, see above.

>  Necessity to opt-out from something you have never subscribed is not the nicest thing.

There is no "necessity to opt-out", and you are not "subscribed" to this.
Nobody has received, nor will receive, any type of notification as a direct result of them getting added to the list. Indeed that is part of the point of me not contacting anyone before adding them to the list, as that could certainly be seen as "spamming" or otherwise undesirable.

Those who wish to be kept informed of certain happenings within the Common Lisp community may want to consider "watching" the repository.

**Comment by Hexstream** [comment]
[Daniel Kochmański (jackdaniel) rushed to send a MALICIOUS, LIBELOUS AND FRAUDULENT complaint to Cloudflare.](https://blog.hexstream.xyz/Daniel-Kochma%C5%84ski-jackdaniel-rushed-to-send-a-MALICIOUS-LIBELOUS-AND-FRAUDULENT-complaint-to-Cloudflare/)

**Comment by Hexstream** [comment]
It's now possible for Common Lispers list members to [register as an Assenter or Objector](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/12).

**This issue is now resolved to my satisfaction.**

**Comment by Hexstream** [comment]
I added [a note](https://common-lispers.hexstreamsoft.com/policies/#minimum-requirements) in the policies about the absence of notifications when getting added to the list. (Refresh.)

**Comment by lispm** [comment]
What a load of bullshit about 'policies'.
Remove Daniel and me from the site.

**Comment by dkochmanski** [comment]
I don't have much more to say in this thread, I've reported abuse to the network provider and wait for the response from them. Reactions of the repository owner are beyond reason so I see no point in arguing here.

**Comment by lispm** [comment]
Instead of endless mental masturbations about 'policies' he could just have updated the site already with the requested removal.

**Comment by Hexstream** [comment]
Yes, I could have decided to be spineless, but I decided otherwise.
I appreciate you both taking the time to express your perspectives.

You may both [register as Objectors](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/12) if you wish, this is the only remedy I have to offer you.

**Comment by lispm** [comment]
I don't want to register for anything. Remove my data. Just do it. Make sure that my data is not visible on your website anymore. I have not entered my data into your software and you are listing me without having asked me. Instead of wasting time, remove me.

**Comment by Hexstream** [comment]
I took the time to [explain my rationale at length](https://common-lispers.hexstreamsoft.com/policies/).
I am looking forward to a healthy public debate.

**Comment by lispm** [comment]
I'm not interested in your rationale. Delete me.

**Comment by Hexstream** [comment]
Behave like an entitled child if you wish, that does not invalidate my [policies](https://common-lispers.hexstreamsoft.com/policies/).

**Comment by lispm** [comment]
Just remove me from your website. Do it.

**Comment by lispm** [comment]
Don't be like child adding funny emojis to my replies. Delete me entry from your website.

**Comment by Hexstream** [comment]
"Debate" continues in #13, for those unaware.

**Comment by lispm** [comment]
There is no debate. Jean-Philippe Paradis repeatedly violates my request to be deleted.

**Comment by Hexstream** [comment]
You are right that there is no debate in that you have repeatedly refused to provide arguments.

I have repeatedly respectfully declined to grant your request because it is fundamentally incompatible with the [policies](https://common-lispers.hexstreamsoft.com/policies/), which nobody has even tried to challenge yet.

**Comment by lispm** [comment]
There is nothing to debate. You have listed my data without my consent. I want to be removed.

**Comment by Hexstream** [comment]
No consent is needed from anyone to republish public information.

***There can be no reasonable expectation of "privacy" regarding information that one willingly and prominently publishes about themselves.***

**I will not destroy my infrastructure every time someone cries.**

**Comment by lispm** [comment]
That's irrelevant. Delete me.

**Comment by Hexstream** [comment]
If facts and logic are irrelevant then I am indeed defenseless.

**Comment by lispm** [comment]
Just delete my data from your website.

**Comment by Hexstream** [comment]
Your request has already been duly processed.
I already did everything I could *responsibly* do.
Please stop wasting everyone's time with your *idemimpotent* requests. (No typo.)

**Comment by lispm** [comment]
You lie. Your website still lists my data.

Remove my data from your website.

**Comment by Hexstream** [comment]
??? I never lie. I said that your request had been duly processed, which it has been. It is clear from the context that duly processing your request ***does not*** involve deleting your entry from the website, as that would be irresponsible.

**Comment by lispm** [comment]
Delete my data from your website.

**Comment by Hexstream** [comment]
You sound like a [broken record](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/13).
Please consult a mental health professional.

**Comment by lispm** [comment]
Delete my data from your website.

**Comment by Hexstream** [comment]
I am no longer entertained by your [antics](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/13).
I empathize with your frustration, but advise you to consult a mental health professional.

**Comment by lispm** [comment]
Delete my data from your website.
